import React, { createContext, useState, useContext, useEffect, useMemo } from 'react';
import type { Locale } from '../types';

type Translations = Record<string, string>;
type LocalizationContextType = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
};

const translations: Record<Locale, Translations> = {
  es: {
    nav_search: 'Búsqueda',
    nav_journal: 'Diario',
    nav_techniques: 'Técnicas',
    nav_profile: 'Perfil',
    footer_text: '© 2024 BioClave. Todos los derechos reservados. Herramienta complementaria de bienestar.',
    symptom_intro_title: 'Tu Guía de Bienestar Emocional',
    symptom_intro_subtitle: 'Ingresa un síntoma, enfermedad o dolencia para explorar su posible origen emocional. Descubre los conflictos subyacentes y comienza tu camino hacia la auto-observación y sanación.',
    symptom_placeholder: 'Busca un síntoma (ej. dolor de garganta, ansiedad...)',
    symptom_button_loading: 'Buscando...',
    symptom_button_search: 'Buscar',
    symptom_error_fetch: 'No se pudo obtener la información. Por favor, intenta de nuevo.',
    symptom_definition: 'Definición',
    symptom_bio_meaning: 'Sentido Biológico ("Para qué")',
    symptom_conflicts: 'Posibles Conflictos Emocionales',
    symptom_tech_info_title: 'Información Técnica',
    symptom_tech_info_layer: 'Capa Embrionaria',
    symptom_tech_info_conflict_type: 'Tipo de Conflicto',
    symptom_tech_info_phases: 'Comportamiento en Fases',
    symptom_reminder: 'Recuerda que estos conflictos son interpretaciones simbólicas y no dogmas. Cada persona vive la realidad de una forma única.',
    journal_title: 'Diario de Auto-observación',
    journal_subtitle: 'Usa este espacio para anotar tus reflexiones, sueños, avances y el seguimiento de tus emociones. La auto-observación es clave en el camino del bienestar.',
    journal_placeholder: 'Escribe tus pensamientos aquí...',
    journal_save_button: 'Guardar Entrada',
    journal_my_entries: 'Mis Entradas',
    journal_no_entries: 'Aún no tienes entradas en tu diario.',
    journal_delete_entry_aria: 'Eliminar entrada',
    techniques_title: 'Caja de Herramientas',
    techniques_subtitle: 'Explora diversas técnicas y protocolos de sanación para liberar emociones, transformar patrones y apoyar tu proceso de bienestar. Selecciona una técnica para aprender más.',
    techniques_loading: 'Cargando explicación...',
    techniques_error_fetch: 'No se pudo cargar la información de la técnica.',
    technique_name_circulo_excelencia: 'Círculo de la Excelencia',
    technique_name_anclaje_cinestesico: 'Anclaje Cinestésico',
    technique_name_reencuadre: 'Cambiar el Significado (Reencuadre)',
    technique_name_linea_tiempo: 'Línea del Tiempo',
    technique_name_psicomagia: 'Psicomagia',
    technique_name_nino_interno: 'Recuperación del Niño Interno',
    technique_name_protocolo_duelo: 'Protocolo de Duelo',
    technique_category_pnl: 'PNL',
    technique_category_actos_simbólicos: 'Actos Simbólicos',
    technique_category_sanación_emocional: 'Sanación Emocional',
    disclaimer_title: 'Aviso Importante',
    disclaimer_p1: 'BioClave es una herramienta de auto-observación y bienestar emocional basada en la biodescodificación. La información proporcionada es para fines educativos y de crecimiento personal.',
    disclaimer_p2: 'No sustituye en ningún caso el diagnóstico, consejo o tratamiento de un profesional de la salud. Consulta siempre a tu médico.',
    disclaimer_button: 'Entendido, acepto',
    profile_title: 'Mi Perfil',
    profile_settings_title: 'Configuración',
    profile_logout_button: 'Cerrar Sesión',
    profile_logout_description: 'Esto restablecerá tu sesión y uso de la aplicación.',
    language_switcher_title: 'Idioma',
    subscription_modal_title: 'Desbloquea Todas las Funciones',
    subscription_modal_subtitle: 'Obtén acceso ilimitado y apoya nuestro proyecto para seguir creciendo.',
    subscription_benefit_1: 'Búsquedas ilimitadas de síntomas',
    subscription_benefit_2: 'Acceso completo a todas las técnicas',
    subscription_benefit_3: 'Análisis de sueños en tu diario (Próximamente)',
    subscription_button_subscribe: 'Suscribirse Ahora',
    subscription_button_later: 'Quizás más tarde',
    subscription_loading: 'Procesando suscripción...',
    profile_subscription_title: 'Estado de la Suscripción',
    profile_status_free: 'Miembro Gratuito',
    profile_status_premium: 'Miembro Premium',
    profile_button_upgrade: 'Pasar a Premium',
    profile_subscription_description_free: 'Tienes 1 búsqueda de síntomas gratuita. Pasa a Premium para acceso ilimitado.',
    profile_subscription_description_premium: '¡Gracias por apoyar BioClave! Disfruta de acceso total.',
  },
  en: {
    nav_search: 'Search',
    nav_journal: 'Journal',
    nav_techniques: 'Techniques',
    nav_profile: 'Profile',
    footer_text: '© 2024 BioClave. All rights reserved. Complementary wellness tool.',
    symptom_intro_title: 'Your Guide to Emotional Well-being',
    symptom_intro_subtitle: 'Enter a symptom, illness, or ailment to explore its possible emotional origin. Discover the underlying conflicts and begin your path to self-awareness and healing.',
    symptom_placeholder: 'Search for a symptom (e.g., sore throat, anxiety...)',
    symptom_button_loading: 'Searching...',
    symptom_button_search: 'Search',
    symptom_error_fetch: 'Could not retrieve information. Please try again.',
    symptom_definition: 'Definition',
    symptom_bio_meaning: 'Biological Meaning ("What for")',
    symptom_conflicts: 'Possible Emotional Conflicts',
    symptom_tech_info_title: 'Technical Information',
    symptom_tech_info_layer: 'Embryonic Layer',
    symptom_tech_info_conflict_type: 'Conflict Type',
    symptom_tech_info_phases: 'Behavior in Phases',
    symptom_reminder: 'Remember that these conflicts are symbolic interpretations, not dogmas. Each person experiences reality in a unique way.',
    journal_title: 'Self-Observation Journal',
    journal_subtitle: 'Use this space to write down your reflections, dreams, progress, and track your emotions. Self-observation is key on the path to well-being.',
    journal_placeholder: 'Write your thoughts here...',
    journal_save_button: 'Save Entry',
    journal_my_entries: 'My Entries',
    journal_no_entries: 'You have no entries in your journal yet.',
    journal_delete_entry_aria: 'Delete entry',
    techniques_title: 'Toolbox',
    techniques_subtitle: 'Explore various healing techniques and protocols to release emotions, transform patterns, and support your well-being process. Select a technique to learn more.',
    techniques_loading: 'Loading explanation...',
    techniques_error_fetch: 'Could not load the technique information.',
    technique_name_circulo_excelencia: 'Circle of Excellence',
    technique_name_anclaje_cinestesico: 'Kinesthetic Anchor',
    technique_name_reencuadre: 'Reframing',
    technique_name_linea_tiempo: 'Timeline',
    technique_name_psicomagia: 'Psychomagic',
    technique_name_nino_interno: 'Inner Child Recovery',
    technique_name_protocolo_duelo: 'Grief Protocol',
    technique_category_pnl: 'NLP',
    technique_category_actos_simbólicos: 'Symbolic Acts',
    technique_category_sanación_emocional: 'Emotional Healing',
    disclaimer_title: 'Important Notice',
    disclaimer_p1: 'BioClave is a tool for self-observation and emotional well-being based on biodecoding. The information provided is for educational and personal growth purposes.',
    disclaimer_p2: 'It does not replace the diagnosis, advice, or treatment of a healthcare professional under any circumstances. Always consult your doctor.',
    disclaimer_button: 'I understand and accept',
    profile_title: 'My Profile',
    profile_settings_title: 'Settings',
    profile_logout_button: 'Log Out',
    profile_logout_description: 'This will reset your session and application usage.',
    language_switcher_title: 'Language',
    subscription_modal_title: 'Unlock All Features',
    subscription_modal_subtitle: 'Get unlimited access and support our project to keep growing.',
    subscription_benefit_1: 'Unlimited symptom searches',
    subscription_benefit_2: 'Full access to all techniques',
    subscription_benefit_3: 'Dream analysis in your journal (Coming Soon)',
    subscription_button_subscribe: 'Subscribe Now',
    subscription_button_later: 'Maybe later',
    subscription_loading: 'Processing subscription...',
    profile_subscription_title: 'Subscription Status',
    profile_status_free: 'Free Member',
    profile_status_premium: 'Premium Member',
    profile_button_upgrade: 'Upgrade to Premium',
    profile_subscription_description_free: 'You have 1 free symptom search. Upgrade to Premium for unlimited access.',
    profile_subscription_description_premium: 'Thanks for supporting BioClave! Enjoy full access.',
  },
  fr: {
    nav_search: 'Recherche',
    nav_journal: 'Journal',
    nav_techniques: 'Techniques',
    nav_profile: 'Profil',
    footer_text: '© 2024 BioClave. Tous droits réservés. Outil de bien-être complémentaire.',
    symptom_intro_title: 'Votre Guide de Bien-être Émotionnel',
    symptom_intro_subtitle: "Entrez un symptôme, une maladie ou un malaise pour explorer son origine émotionnelle possible. Découvrez les conflits sous-jacents et commencez votre chemin vers la conscience de soi et la guérison.",
    symptom_placeholder: 'Rechercher un symptôme (ex: mal de gorge, anxiété...)',
    symptom_button_loading: 'Recherche...',
    symptom_button_search: 'Rechercher',
    symptom_error_fetch: "Impossible de récupérer l'information. Veuillez réessayer.",
    symptom_definition: 'Définition',
    symptom_bio_meaning: 'Sens Biologique ("Pourquoi faire")',
    symptom_conflicts: 'Conflits Émotionnels Possibles',
    symptom_tech_info_title: 'Informations Techniques',
    symptom_tech_info_layer: 'Couche Embryonnaire',
    symptom_tech_info_conflict_type: 'Type de Conflit',
    symptom_tech_info_phases: 'Comportement en Phases',
    symptom_reminder: 'Rappelez-vous que ces conflits sont des interprétations symboliques, pas des dogmes. Chaque personne vit la réalité de manière unique.',
    journal_title: "Journal d'Auto-observation",
    journal_subtitle: "Utilisez cet espace pour noter vos réflexions, vos rêves, vos progrès et suivre vos émotions. L'auto-observation est la clé sur le chemin du bien-être.",
    journal_placeholder: 'Écrivez vos pensées ici...',
    journal_save_button: "Enregistrer l'Entrée",
    journal_my_entries: 'Mes Entrées',
    journal_no_entries: "Vous n'avez pas encore d'entrées dans votre journal.",
    journal_delete_entry_aria: "Supprimer l'entrée",
    techniques_title: 'Boîte à Outils',
    techniques_subtitle: "Explorez diverses techniques et protocoles de guérison pour libérer les émotions, transformer les schémas et soutenir votre processus de bien-être. Sélectionnez une technique pour en savoir plus.",
    techniques_loading: 'Chargement de l’explication...',
    techniques_error_fetch: 'Impossible de charger les informations de la technique.',
    technique_name_circulo_excelencia: "Cercle d'Excellence",
    technique_name_anclaje_cinestesico: 'Ancrage Kinesthésique',
    technique_name_reencuadre: 'Recadrage',
    technique_name_linea_tiempo: 'Ligne du Temps',
    technique_name_psicomagia: 'Psychomagie',
    technique_name_nino_interno: "Récupération de l'Enfant Intérieur",
    technique_name_protocolo_duelo: 'Protocole de Deuil',
    technique_category_pnl: 'PNL',
    technique_category_actos_simbólicos: 'Actes Symboliques',
    technique_category_sanación_emocional: 'Guérison Émotionnelle',
    disclaimer_title: 'Avis Important',
    disclaimer_p1: "BioClave est un outil d'auto-observation et de bien-être émotionnel basé sur le biodécodage. Les informations fournies sont à des fins éducatives et de croissance personnelle.",
    disclaimer_p2: 'Il ne remplace en aucun cas le diagnostic, les conseils ou le traitement d’un professionnel de la santé. Consultez toujours votre médecin.',
    disclaimer_button: 'Je comprends et j’accepte',
    profile_title: 'Mon Profil',
    profile_settings_title: 'Paramètres',
    profile_logout_button: 'Se Déconnecter',
    profile_logout_description: 'Cela réinitialisera votre session et votre utilisation de l’application.',
    language_switcher_title: 'Langue',
    subscription_modal_title: 'Débloquez toutes les fonctionnalités',
    subscription_modal_subtitle: 'Obtenez un accès illimité et soutenez notre projet pour continuer à grandir.',
    subscription_benefit_1: 'Recherches de symptômes illimitées',
    subscription_benefit_2: 'Accès complet à toutes les techniques',
    subscription_benefit_3: 'Analyse des rêves dans votre journal (Bientôt disponible)',
    subscription_button_subscribe: 'S\'abonner maintenant',
    subscription_button_later: 'Peut-être plus tard',
    subscription_loading: 'Traitement de l\'abonnement...',
    profile_subscription_title: 'Statut de l\'abonnement',
    profile_status_free: 'Membre Gratuit',
    profile_status_premium: 'Membre Premium',
    profile_button_upgrade: 'Passer à Premium',
    profile_subscription_description_free: 'Vous avez 1 recherche de symptôme gratuite. Passez à Premium pour un accès illimité.',
    profile_subscription_description_premium: 'Merci de soutenir BioClave ! Profitez d\'un accès complet.',
  },
  it: {
    nav_search: 'Ricerca',
    nav_journal: 'Diario',
    nav_techniques: 'Tecniche',
    nav_profile: 'Profilo',
    footer_text: '© 2024 BioClave. Tutti i diritti riservati. Strumento di benessere complementare.',
    symptom_intro_title: 'La Tua Guida al Benessere Emotivo',
    symptom_intro_subtitle: "Inserisci un sintomo, una malattia o un disturbo per esplorarne la possibile origine emotiva. Scopri i conflitti sottostanti e inizia il tuo percorso verso l'autoconsapevolezza e la guarigione.",
    symptom_placeholder: 'Cerca un sintomo (es. mal di gola, ansia...)',
    symptom_button_loading: 'Ricerca in corso...',
    symptom_button_search: 'Cerca',
    symptom_error_fetch: "Impossibile recuperare le informazioni. Per favore, riprova.",
    symptom_definition: 'Definizione',
    symptom_bio_meaning: 'Senso Biologico ("A che serve")',
    symptom_conflicts: 'Possibili Conflitti Emotivi',
    symptom_tech_info_title: 'Informazioni Tecniche',
    symptom_tech_info_layer: 'Foglietto Embrionale',
    symptom_tech_info_conflict_type: 'Tipo di Conflitto',
    symptom_tech_info_phases: 'Comportamento nelle Fasi',
    symptom_reminder: "Ricorda che questi conflitti sono interpretazioni simboliche, non dogmi. Ogni persona vive la realtà in un modo unico.",
    journal_title: 'Diario di Auto-osservazione',
    journal_subtitle: "Usa questo spazio per annotare le tue riflessioni, i sogni, i progressi e monitorare le tue emozioni. L'auto-osservazione è la chiave nel percorso verso il benessere.",
    journal_placeholder: 'Scrivi qui i tuoi pensieri...',
    journal_save_button: 'Salva Voce',
    journal_my_entries: 'Le Mie Voci',
    journal_no_entries: 'Non hai ancora voci nel tuo diario.',
    journal_delete_entry_aria: 'Elimina voce',
    techniques_title: 'Cassetta degli Attrezzi',
    techniques_subtitle: "Esplora varie tecniche e protocolli di guarigione per liberare emozioni, trasformare schemi e sostenere il tuo processo di benessere. Seleziona una tecnica per saperne di più.",
    techniques_loading: 'Caricamento spiegazione...',
    techniques_error_fetch: 'Impossibile caricare le informazioni sulla tecnica.',
    technique_name_circulo_excelencia: 'Cerchio dell’Eccellenza',
    technique_name_anclaje_cinestesico: 'Ancoraggio Cinestesico',
    technique_name_reencuadre: 'Ristrutturazione',
    technique_name_linea_tiempo: 'Linea del Tempo',
    technique_name_psicomagia: 'Psicomagia',
    technique_name_nino_interno: 'Recupero del Bambino Interiore',
    technique_name_protocolo_duelo: 'Protocollo del Lutto',
    technique_category_pnl: 'PNL',
    technique_category_actos_simbólicos: 'Atti Simbolici',
    technique_category_sanación_emocional: 'Guarigione Emotiva',
    disclaimer_title: 'Avviso Importante',
    disclaimer_p1: "BioClave è uno strumento di auto-osservazione e benessere emotivo basato sulla biodecodifica. Le informazioni fornite sono a scopo educativo e di crescita personale.",
    disclaimer_p2: 'Non sostituisce in nessun caso la diagnosi, il consiglio o il trattamento di un professionista sanitario. Consulta sempre il tuo medico.',
    disclaimer_button: 'Ho capito, accetto',
    profile_title: 'Il Mio Profilo',
    profile_settings_title: 'Impostazioni',
    profile_logout_button: 'Esci',
    profile_logout_description: 'Questo reimposterà la tua sessione e l’utilizzo dell’applicazione.',
    language_switcher_title: 'Lingua',
    subscription_modal_title: 'Sblocca tutte le funzionalità',
    subscription_modal_subtitle: 'Ottieni accesso illimitato e sostieni il nostro progetto per continuare a crescere.',
    subscription_benefit_1: 'Ricerche di sintomi illimitate',
    subscription_benefit_2: 'Accesso completo a tutte le tecniche',
    subscription_benefit_3: 'Analisi dei sogni nel tuo diario (Prossimamente)',
    subscription_button_subscribe: 'Abbonati Ora',
    subscription_button_later: 'Forse più tardi',
    subscription_loading: 'Elaborazione abbonamento...',
    profile_subscription_title: 'Stato Abbonamento',
    profile_status_free: 'Membro Gratuito',
    profile_status_premium: 'Membro Premium',
    profile_button_upgrade: 'Passa a Premium',
    profile_subscription_description_free: 'Hai 1 ricerca di sintomi gratuita. Passa a Premium per un accesso illimitato.',
    profile_subscription_description_premium: 'Grazie per supportare BioClave! Goditi l\'accesso completo.',
  },
  zh: {
    nav_search: '搜索',
    nav_journal: '日记',
    nav_techniques: '技巧',
    nav_profile: '个人资料',
    footer_text: '© 2024 BioClave。版权所有。辅助健康工具。',
    symptom_intro_title: '您的情绪健康指南',
    symptom_intro_subtitle: '输入一个症状、疾病或不适，探索其可能的情感根源。发现潜在的冲突，开始您的自我意识和疗愈之路。',
    symptom_placeholder: '搜索症状（例如：喉咙痛，焦虑...）',
    symptom_button_loading: '搜索中...',
    symptom_button_search: '搜索',
    symptom_error_fetch: '无法获取信息。请再试一次。',
    symptom_definition: '定义',
    symptom_bio_meaning: '生物学意义（“为了什么”）',
    symptom_conflicts: '可能的情感冲突',
    symptom_tech_info_title: '技术信息',
    symptom_tech_info_layer: '胚层',
    symptom_tech_info_conflict_type: '冲突类型',
    symptom_tech_info_phases: '阶段行为',
    symptom_reminder: '请记住，这些冲突是象征性的解释，而不是教条。每个人都以独特的方式体验现实。',
    journal_title: '自我观察日记',
    journal_subtitle: '利用这个空间记录您的反思、梦想、进步并跟踪您的情绪。自我观察是通往健康之路的关键。',
    journal_placeholder: '在这里写下您的想法...',
    journal_save_button: '保存条目',
    journal_my_entries: '我的条目',
    journal_no_entries: '您的日记中还没有条目。',
    journal_delete_entry_aria: '删除条目',
    techniques_title: '工具箱',
    techniques_subtitle: '探索各种疗愈技巧和方案，以释放情绪、转变模式并支持您的健康过程。选择一个技巧以了解更多信息。',
    techniques_loading: '正在加载解释...',
    techniques_error_fetch: '无法加载技巧信息。',
    technique_name_circulo_excelencia: '卓越圈',
    technique_name_anclaje_cinestesico: '动觉锚定',
    technique_name_reencuadre: '重构',
    technique_name_linea_tiempo: '时间线',
    technique_name_psicomagia: '心理魔术',
    technique_name_nino_interno: '内在小孩复原',
    technique_name_protocolo_duelo: '哀悼协议',
    technique_category_pnl: 'NLP',
    technique_category_actos_simbólicos: '象征性行为',
    technique_category_sanación_emocional: '情绪疗愈',
    disclaimer_title: '重要声明',
    disclaimer_p1: 'BioClave 是一款基于生物解码的自我观察和情绪健康工具。所提供的信息仅用于教育和个人成长目的。',
    disclaimer_p2: '在任何情况下，它都不能替代医疗专业人员的诊断、建议或治疗。请务必咨询您的医生。',
    disclaimer_button: '我理解并接受',
    profile_title: '我的个人资料',
    profile_settings_title: '设置',
    profile_logout_button: '登出',
    profile_logout_description: '这将重置您的会话和应用程序使用情况。',
    language_switcher_title: '语言',
    subscription_modal_title: '解锁所有功能',
    subscription_modal_subtitle: '获取无限访问权限并支持我们的项目持续发展。',
    subscription_benefit_1: '无限次症状搜索',
    subscription_benefit_2: '完全访问所有技巧',
    subscription_benefit_3: '日记中的梦境分析（即将推出）',
    subscription_button_subscribe: '立即订阅',
    subscription_button_later: '以后再说',
    subscription_loading: '正在处理订阅...',
    profile_subscription_title: '订阅状态',
    profile_status_free: '免费会员',
    profile_status_premium: '高级会员',
    profile_button_upgrade: '升级到高级版',
    profile_subscription_description_free: '您有1次免费症状搜索。升级到高级版以获得无限访问权限。',
    profile_subscription_description_premium: '感谢支持 BioClave！享受完全访问权限。',
  },
};


const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const savedLocale = typeof window !== 'undefined' ? localStorage.getItem('bioclave_locale') : 'es';
    return (savedLocale && Object.keys(translations).includes(savedLocale)) ? savedLocale as Locale : 'es';
  });

  useEffect(() => {
    localStorage.setItem('bioclave_locale', locale);
  }, [locale]);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
  };

  const t = useMemo(() => (key: string): string => {
    return translations[locale][key] || translations['es'][key] || key;
  }, [locale]);

  return (
    <LocalizationContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = (): LocalizationContextType => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};